- name: Start MySQL Container
  docker_container:
    name: db
    image: "mysql:5.7"
    env:
      MYSQL_DATABASE: "microblog"
      MYSQL_USER: "microblog"
      MYSQL_PASSWORD: "12345"
      MYSQL_ROOT_PASSWORD: "12345"
    volumes:
      - db_data:/var/lib/mysql
    restart_policy: always
    published_ports:
      - "3306:3306"
