version: "3"
networks:
    apinetwork:

services:
    microblog:
        image: prod
        build:
            context: .
            dockerfile: docker/Dockerfile_prod
        depends_on:
            - mysql
        environment:
            - SECRET_KEY=my-secret-key
            - DATABASE_URL=mysql+pymysql://microblog:12345@dbserver/microblog
        ports:
            - "8000:5000"
        links:
            - mysql:dbserver
        networks:
            apinetwork:
        restart: always

    mysql:
        image: mysql/mysql-server:5.7
        container_name: mysql
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=microblog
            - MYSQL_USER=microblog
            - MYSQL_PASSWORD=12345
        networks:
            apinetwork:
        restart: always

    test:
        image: test
        build:
            context: .
            dockerfile: docker/Dockerfile_test
        volumes:
            - ./app:/microblog/app
            - ./tests:/microblog/tests
        depends_on:
            - mysql
        command: ["./test_startup.sh"]
