# Use a base image with the necessary tools and dependencies for testing
FROM python:3.8

# Set the working directory
WORKDIR /microblog

COPY requirements/prod.txt ./
COPY requirements/test.txt ./
COPY run_make_test.sh ./
COPY Makefile ./
COPY .pylintrc ./
COPY pytest.ini ./

# Install dependencies from test.txt
RUN pip install --no-cache-dir -r test.txt

# Make the script executable
RUN chmod +x run_make_test.sh
