name: CI/CD

on:
  release:
    types: [created]
  
jobs:
  test:
    uses: ./.github/workflows/test.yml

  dockerpush:
    uses: ./.github/workflows/dockerpush.yml
    needs: test
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest
    needs: [test, dockerpush]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
